### ISSUE TITLE
Commercial license for x264vfw

### ISSUE THREAD

**Issue by staylorftr** [MasterNobody/x264vfw#3]
Hi @MasterNobody, we're looking to license x264vfw in a commercial product. We already have licensing from MPEG LA and x264. I notice this repo is GPL-2.0, which isn't compatible with our product - but since you appear to be the only contributor, could we have a discussion about a commercial license? Thanks for your help.

**Comment by MasterNobody** [comment]
Hi. I doubt it possible from legal point because I am not original author of some of this code. x264vfw was forked from parts of vfw-code which existed in x264 codebase but was removed from there long before x264 commercial license appeared (so this vfw-code is probably not covered by it). And while I changed a lot of code, I can't say that all of this original code was rewritten.

**Comment by staylorftr** [comment]
All right then, no worries. Thanks so much for replying!
